var lines = document.getElementsByClassName('ct-grid-lines');
if (lines.length){
    document.body.removeChild(lines[0]);
}
else {
    document.body.innerHTML += [
    '<div class="ct-grid-lines">',
        '<div class="container with-xlarge">',
            '<div class="row is-visible-s">',
                '<div class="col-s-1"></div>',
                '<div class="col-s-1"></div>',
                '<div class="col-s-1"></div>',
                '<div class="col-s-1"></div>',
            '</div>',
            '<div class="row is-visible-m is-visible-l">',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
                '<div class="col-m-1 col-l-1"></div>',
            '</div>',
            '<div class="row is-visible-xl">',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
                '<div class="col-xl-1"></div>',
            '</div>',
        '</div>',
    '</div>'].join("\n");
}
